### ISSUE TITLE
Wrong pin number in ilidriver.c

### ISSUE THREAD

**Issue by kagouraki** [pypilot/micropython_ugfx#1]
I am trying to connect a TFT SPI 3.2 inch display with ILI9341 to an esp32 LOLIN32. I have a TTGO T-Display 1.14 Inch LCD and works perfect with the micropython file you provided in this thread 

https://forum.openmarine.net/showthread.php?tid=3849&page=4
plus the "make upload" from HAT directory

When i replicate the steps for the Lolin32 with the 3.2 display i get nothing on the screen. I connected the pins of the screen as the product description of the TTGO diplay says.

![screen](https://user-images.githubusercontent.com/6173967/232068233-bef29b96-e5ac-4b19-a06e-8ad72cf41702.jpg)

Notice the RST pin. It says pin 23 but in your ilidriver.c file the RST pin is 20. There is no gpio20 on the esp32.

**Comment by seandepagnier** [comment]
If you change the pin number in the code does it work?

Different boards use different pins.

**Comment by kagouraki** [comment]
Yes i changed the RST from 20 to 23, compiled micropython with ugfx again and the screen works. Tomorrow i will modify the driver because the screen has inverted collors, is mirrored, i want portrait and the size is small. 

I forked and made another branch. If i manage to do this i will push a commit and remember this time not to change you defaults like the touchbutton addition i made so you can merge is directly. 

My setup will be a stationary pypilot remote powered by ships service battery and touchpads instead of buttons(easier waterproofing). Of course i will share pcb,case parts and a guide when i am done.

You made an awesome work. I hope you had more comments though. I am a hobbist and my regular job has nothing to do with pc programing. 😅 Takes time to understand but baby steps !
